# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/ein ./cmd/ein.go"
bin = "./tmp/ein"
full_bin = "./tmp/ein"
args_bin = ["server"]
log = "tmp/air.log"
delay = 1000  # ms
stop_signal = "SIGTERM"

[log]
time = true

[misc]
clean_on_exit = true
