# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/ein.go"
bin = "tmp/main"
full_bin = "tmp/main"
args_bin = ["server"]
log = "tmp/air.log"
delay = 1000                                # ms
stop_signal = "SIGTERM"

[log]
time = false

[misc]
clean_on_exit = true
