name: Delivery

on:
  push:
    branches:
      - main
jobs:
  install-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Install go deps
        run: go mod tidy

      - name: Build packages
        run: go build -v ./...

      - name: "Tag"
        uses: anothrNick/github-tag-action@1.36.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
    env:
      GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
