name: Deploy

on: 
    push: 
        branches:
            - main
jobs: 
    install-deps:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                go-version: [ '1.21.x', '1.22.x' ]
        steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version:  ${{ matrix.go-version }}

        - name: Install go deps
          run: go mod tidy

        - name: Build packages 
          run: go build -v ./...

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@master
          with:
            version: latest
            args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

